<?xml version="1.0"?>
<package format="2">
  <name>urg_node_msgs</name>
  <version>0.15.0</version>
  <description>Message used by urg_node pkg</description>
  <maintainer email="cribeiromendes@locusrobotics.com">Carlos Mendes</maintainer>
  <license>BSD</license>
  <buildtool_depend>catkin</buildtool_depend>
  <depend>message_generation</depend>
  <depend>std_msgs</depend>
  <exec_depend>message_runtime</exec_depend>
</package>
